# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b018260857e4d3a597dd2a737d6e9777"
name = "remix chat"
handle = "remix-chat-129"
application_url = "https://preston-ing-willing-raid.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ti-amor.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://preston-ing-willing-raid.trycloudflare.com/auth/callback",
  "https://preston-ing-willing-raid.trycloudflare.com/auth/shopify/callback",
  "https://preston-ing-willing-raid.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
